# -*- coding: utf-8 -*-
"""Project 15 Run_on_colab_Detection_of_Covid_19_from_Chest_X_ray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jG-4ls5YTg-x2e6lL-eDuSF1uEB6Wl6

# Detection of Covid-19 from Chest-X-ray
"""

# Import the required modules
import numpy as np
import pandas as pd
import tensorflow as tf
import keras_preprocessing
from keras_preprocessing import image
from keras_preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

!pip install keras_preprocessing

"""# Data ingesting of Covid 19 images

## COVID and Normal dataset directory
## Method No 1: Using Kaggle
"""

#install kaggle
! pip install kaggle

! kaggle datasets download alifrahman/covid19-chest-xray-image-dataset

! mkdir train

! unzip /content/covid19-chest-xray-image-dataset.zip

import os

# Dynamically set BASIS_DIR using relative paths
if os.path.exists('dataset'):
    BASIS_DIR = 'dataset'
elif os.path.exists('COVID_CHEST_XRAY'):
    BASIS_DIR = 'COVID_CHEST_XRAY'
else:
    BASIS_DIR = './dataset'

CLASSES = ["covid", "normal"]

"""# Image augmentation process:"""

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    horizontal_flip=True,
    shear_range = 0.2,
    zoom_range = 0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    fill_mode = 'nearest',

    #split dataset to training(80%) and validation(20%):
    validation_split=0.2
)

"""# Training dataset and Validation dataset:"""

train_data = train_datagen.flow_from_directory(
    directory=BASIS_DIR,
    target_size=(299, 299),
    batch_size=32,
    shuffle=True,
    class_mode='binary',
    subset='training',
    classes=CLASSES
    )

val_data = train_datagen.flow_from_directory(
    directory=BASIS_DIR,
    target_size=(299, 299),
    batch_size=32,
    shuffle=True,
    class_mode='binary',
    subset='validation',
    classes=CLASSES
    )

"""# Using sequential model:"""

model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(299, 299, 3)),
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.summary()

# (filter_height*filter_width*number_of_channels+1)*number_of_filters
(3*3*32+1)*32

# Compiling model with 'adam' optimizer loss function 'binary_crossentropy'
model.compile(loss='binary_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy']
             )

# Training process:
number_epochs = 3
# You can change number_epochs above. But the bigger the value, the more time it takes for training
history = model.fit(train_data, epochs=number_epochs,
                    validation_data=val_data, verbose=2)

# Plotting training accuracy and validation accuracy
plt.plot(history.history['accuracy'], 'r', label='Accuracy Training')
plt.plot(history.history['val_accuracy'], 'b', label='Accuracy Validation')
plt.title('Accuracy Training and Validation')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(loc=0)
plt.show()

# Plotting training loss and validation loss
plt.plot(history.history['loss'], 'r', label='Loss Training')
plt.plot(history.history['val_loss'], 'b', label='Loss Validation')
plt.title('Loss Training and Validation')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(loc=0)
plt.show()

# Save the compiled model in both native Keras format and legacy H5 format
model.save('model.keras')
model.save('model.h5')
print("Model saved successfully as model.keras and model.h5")

"""# Test random image"""

import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt

# Assuming you have a pre-trained model saved as 'your_model.h5'
# Check for saved model
if os.path.exists('model.keras'):
    model = load_model('model.keras')
    print("Loaded model.keras")
elif os.path.exists('model.h5'):
    model = load_model('model.h5')
    print("Loaded model.h5")
else:
    print("No model file found to load.")

# Dynamically look for any chest X-ray image in the dataset folder for testing
path = None
for root, dirs, files in os.walk(BASIS_DIR):
    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            path = os.path.join(root, file)
            break
    if path:
        break

if path:
    img = image.load_img(path, target_size=(299, 299))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    result = model.predict(img_array)

    # Assuming your model output has two classes (COVID and Normal)
    threshold = 0.5
    prediction = "COVID" if result[0][0] > threshold else "NORMAL"
    print(f"Sample prediction for {path}: {prediction}")

    # Display the image
    plt.imshow(img)
    plt.title(f"Prediction: {prediction}")
    plt.axis('off')  # Hide the axes
    plt.show()
else:
    print("No sample images found in dataset directory for testing.")

